"""MCP config builders for the puffo-core agent runtime.

Every managed runtime spawns the same puffo_core MCP server through its
native CLI transport. This
module centralises env-var names, the MCP subprocess command line,
and the JSON config shape claude-code expects.

Tool names appear as ``mcp__puffo__<tool>`` when invoked from
claude-code; allowlists / ``--permission-prompt-tool`` reference
that form.
"""

from __future__ import annotations

import json
import logging
import re
import site
import os
import sys
from pathlib import Path

logger = logging.getLogger(__name__)

MCP_SERVER_NAME = "puffo"
_PACKAGE_IMPORT_ROOT = Path(__file__).resolve().parents[2]

# Claude Code reasoning-effort values.
INFERENCE_LEVELS = ("low", "medium", "high", "xhigh")

# codex model_reasoning_effort values.
REASONING_EFFORTS = ("minimal", "low", "medium", "high")


def supported_inference_levels(harness: str) -> tuple[str, ...]:
    """Reasoning-effort values implemented by a specific harness."""
    if harness == "codex":
        return REASONING_EFFORTS
    if harness == "claude-code":
        return INFERENCE_LEVELS
    return ()

_TOML_BARE_KEY = re.compile(r"[A-Za-z0-9_-]+")


PUFFO_CORE_TOOL_NAMES = (
    "send_message",
    "send_message_with_attachments",
    "list_spaces",
    "list_channels_in_all_spaces",
    "list_channels_in_space",
    "list_channel_members",
    "get_channel_history",
    "get_dm_history",
    "get_thread_history",
    "get_post",
    "get_post_segment",
    "get_user_info",
    "whoami",
    "install_skill",
    "uninstall_skill",
    "list_skills",
    "install_mcp_server",
    "uninstall_mcp_server",
    "list_mcp_servers",
    "install_host_mcp",
    "sync_host_mcp",
    "leave_space",
    "leave_channel",
    "get_dm_allowlists",
    "get_dm_blocklists",
    "add_dm_allowlist",
    "update_dm_blocklist",
    "refresh",
    # M3 memory tools (registered by mcp.memory_tools).
    "create_note",
    "patch_note",
    "append_note",
    "create_briefing_topic",
    "patch_briefing_topic",
    "append_recollection",
    "read_memory_file",
    "read_memory_files",
    "search_memory",
    "search_imports",
    # M4 memory status / recall / history tools (read-only; registered
    # by mcp.memory_tools).
    "get_memory_status",
    "get_memory_file_status",
    "list_memory_files",
    "get_memory_history_status",
    "get_memory_history",
)
PUFFO_CORE_TOOL_FQNS = tuple(
    f"mcp__{MCP_SERVER_NAME}__{t}" for t in PUFFO_CORE_TOOL_NAMES
)


def cli_mcp_config_doc(
    *,
    command: str,
    args: list[str],
    env: dict[str, str],
) -> dict:
    """Build the document for claude-code's ``--mcp-config`` flag
    (top-level ``mcpServers`` key, stdio schema)."""
    return {
        "mcpServers": {
            MCP_SERVER_NAME: {
                "type": "stdio",
                "command": command,
                "args": list(args),
                "env": dict(env),
            }
        }
    }


def write_cli_mcp_config(
    dest: Path,
    *,
    command: str,
    args: list[str],
    env: dict[str, str],
) -> Path:
    """Serialise the CLI MCP config to ``dest``. Returns the path."""
    doc = cli_mcp_config_doc(command=command, args=args, env=env)
    dest.parent.mkdir(parents=True, exist_ok=True)
    dest.write_text(json.dumps(doc, indent=2), encoding="utf-8")
    return dest


def write_codex_mcp_config(
    dest: Path,
    *,
    command: str | None = None,
    args: list[str] | None = None,
    env: dict[str, str] | None = None,
    extra_servers: dict[str, dict] | None = None,
    inference_level: str | None = None,
    provider: dict | None = None,
) -> Path:
    """Serialise the per-agent codex config.toml.

    Always emits ``cli_auth_credentials_store = "file"`` so codex
    reads/writes ``$CODEX_HOME/auth.json`` instead of macOS Keychain
    (the daemon's ``CodexFileBackend`` + ``sync_host_codex_auth_view``
    only work in file-mode auth).

    Emits ``[mcp_servers.<name>]`` for the puffo_core stdio server
    (when ``command`` is given) + every ``extra_servers`` entry (host
    MCPs read by ``read_host_codex_mcp_servers``). The puffo entry
    shadows any ``puffo``-keyed host entry to avoid duplicate keys.
    """
    dest.parent.mkdir(parents=True, exist_ok=True)

    lines: list[str] = [
        "# Auto-generated by puffo-agent — do not edit by hand.",
        "# Regenerated on every worker start; manual edits are lost.",
        "",
        'cli_auth_credentials_store = "file"',
    ]
    # top-level key must precede [mcp_servers.*] tables
    if inference_level:
        if inference_level in REASONING_EFFORTS:
            lines.append(f'model_reasoning_effort = "{inference_level}"')
        else:
            logger.warning(
                "dropping inference_level %r for codex (no matching "
                "model_reasoning_effort; expected one of %s)",
                inference_level, ", ".join(REASONING_EFFORTS),
            )
    # LiteLLM (or any OpenAI-compatible gateway) custom provider. When present,
    # codex talks to ``base_url`` via the Responses API using the bearer key in
    # ``env_key`` (the agent's virtual key) instead of its native ChatGPT OAuth.
    # ``wire_api = "responses"`` is REQUIRED — codex dropped Chat Completions.
    if provider and provider.get("base_url"):
        raw_name = provider.get("name") or "litellm"
        key = _toml_key(raw_name)
        model = provider.get("model") or ""
        if model:
            lines.append(f'model = "{_toml_escape(model)}"')
        lines.append(f'model_provider = "{_toml_escape(raw_name)}"')
        lines.append("")
        lines.append(f"[model_providers.{key}]")
        lines.append(
            f'name = "{_toml_escape(provider.get("display_name") or "LiteLLM gateway")}"'
        )
        lines.append(f'base_url = "{_toml_escape(provider["base_url"])}"')
        lines.append(
            f'env_key = "{_toml_escape(provider.get("env_key") or "OPENAI_API_KEY")}"'
        )
        lines.append(f'wire_api = "{_toml_escape(provider.get("wire_api") or "responses")}"')
    # Host extras first so the puffo entry below shadows any duplicate.
    for name, spec in sorted((extra_servers or {}).items()):
        if name == MCP_SERVER_NAME:
            continue
        lines += _emit_codex_mcp_block(name, spec)
    if command is not None:
        puffo_spec: dict = {"command": command, "args": list(args or [])}
        if env:
            puffo_spec["env"] = dict(env)
        lines += _emit_codex_mcp_block(MCP_SERVER_NAME, puffo_spec)
    lines.append("")
    dest.write_text("\n".join(lines), encoding="utf-8")
    return dest


def _emit_codex_mcp_block(name: str, spec: dict) -> list[str]:
    """Emit a ``[mcp_servers.<name>]`` block. codex selects transport
    by which key is present (``url`` → http, ``command`` → stdio).
    Never emit ``type`` — codex doesn't recognise it."""
    key = _toml_key(name)
    out: list[str] = ["", f"[mcp_servers.{key}]"]
    url = spec.get("url")
    if isinstance(url, str) and url:
        out.append(f'url = "{_toml_escape(url)}"')
        bearer = spec.get("bearer_token_env_var")
        if isinstance(bearer, str) and bearer:
            out.append(f'bearer_token_env_var = "{_toml_escape(bearer)}"')
        headers = spec.get("http_headers")
        if isinstance(headers, dict) and headers:
            inline = ", ".join(
                f'"{_toml_escape(str(k))}" = "{_toml_escape(str(v))}"'
                for k, v in sorted(headers.items())
            )
            out.append(f'http_headers = {{ {inline} }}')
    else:
        cmd = str(spec.get("command", ""))
        out.append(f'command = "{_toml_escape(cmd)}"')
        args = spec.get("args") or []
        out.append(
            "args = ["
            + ", ".join(f'"{_toml_escape(str(a))}"' for a in args)
            + "]"
        )
    env = spec.get("env") or {}
    if env:
        out.append("")
        out.append(f"[mcp_servers.{key}.env]")
        for k, v in sorted(env.items()):
            out.append(f'{_toml_key(k)} = "{_toml_escape(str(v))}"')
    return out


def _toml_key(name: str) -> str:
    # Bare key if it matches the TOML bare-key charset; otherwise quote
    # as basic-string key (prevents dots from creating nested tables).
    if _TOML_BARE_KEY.fullmatch(name):
        return name
    return f'"{_toml_escape(name)}"'


def _toml_escape(s: str) -> str:
    # Only backslash + double-quote need escaping in basic strings for
    # the path / arg / env shapes we emit. Newlines aren't expected.
    return s.replace("\\", "\\\\").replace('"', '\\"')


def default_python_executable() -> str:
    """Path to the daemon's own interpreter — the right choice for
    SDK / cli-local, where the MCP runs in the same interpreter tree.
    """
    return sys.executable or "python3"


# cli-local adapter overrides ``HOME`` (and ``USERPROFILE``) on the
# claude subprocess so each agent has its own ``~/.claude``. The
# MCP server claude spawns inherits that HOME, which makes Python's
# user-site path resolve to ``<per-agent-home>/Library/Python/...``
# (macOS) / ``<per-agent-home>/AppData/...`` (Windows) — a directory
# that doesn't exist on disk. Result: ``import mcp`` (installed in
# the real user's user-site) raises ModuleNotFoundError, the MCP
# server exits, and the agent loses every ``mcp__puffo__*`` tool.
#
# ``PYTHONUSERBASE`` overrides where Python computes user-site from,
# independent of HOME. By snapshotting ``site.getuserbase()`` while
# we're in the daemon process (real HOME) and forwarding it via the
# MCP env, the spawned subprocess locates the same user-site the
# daemon does — ``.pth`` files included, so editable installs of
# ``puffo_agent`` keep working too.
_REAL_USER_BASE = site.getuserbase()


def _python_user_base_env(runtime_kind: str) -> dict[str, str]:
    """Env additions that pin ``PYTHONUSERBASE`` so subprocesses with
    a per-agent HOME still resolve user-site to the daemon's real
    base. Returns an empty dict if ``site.getuserbase()`` produced
    nothing usable (defensive — shouldn't happen on supported
    platforms, but failing silent beats taking the MCP down).

    ``cli-docker`` is excluded: the MCP runs inside a container with
    its own Python install and baked-in deps, so the host's user-base
    path is meaningless there (a non-existent dir Python would just
    skip). Forwarding a host-relative path into the container env is
    semantically wrong even if harmless, so we keep the env clean."""
    if runtime_kind == "cli-docker":
        return {}
    if not _REAL_USER_BASE:
        return {}
    return {"PYTHONUSERBASE": _REAL_USER_BASE}


def _mcp_pythonpath(runtime_kind: str) -> str:
    """Pin the MCP subprocess to the package tree loaded by the daemon."""
    if "docker" in runtime_kind:
        return ""

    entries = [str(_PACKAGE_IMPORT_ROOT)]
    inherited = os.environ.get("PYTHONPATH")
    if inherited:
        daemon_cwd = Path.cwd()
        for raw_entry in inherited.split(os.pathsep):
            entry = Path(raw_entry or ".").expanduser()
            if not entry.is_absolute():
                entry = daemon_cwd / entry
            entries.append(str(entry.resolve()))
    return os.pathsep.join(dict.fromkeys(entries))


# ── puffo-core config builders ────────────────────────────────────


def puffo_core_mcp_env(
    *,
    slug: str,
    device_id: str,
    server_url: str,
    space_id: str = "",
    keystore_dir: str,
    workspace: str,
    agent_id: str = "",
    data_service_url: str = "http://127.0.0.1:63386",
    rpc_url: str = "http://127.0.0.1:63385",
    runtime_kind: str = "",
    harness: str = "",
    memory_dir: str = "",
    transport: str = "",
) -> dict[str, str]:
    """Env dict for the puffo-core MCP subprocess. The MCP never
    touches ``messages.db`` or ``~/.claude.json`` directly — the
    daemon owns both. cli-docker rewrites the loopback URLs to
    ``host.docker.internal``. ``memory_dir`` (optional) pins the
    memory root for the M3 memory tools; when empty the server falls
    back to the workspace-sibling ``memory/`` dir."""
    from ..portal.local_service_auth import (
        LOCAL_SERVICE_TOKEN_ENV,
        issue_local_service_token,
    )

    effective_agent_id = agent_id or slug
    env: dict[str, str] = {
        "PUFFO_CORE_SLUG": slug,
        "PUFFO_CORE_DEVICE_ID": device_id,
        "PUFFO_CORE_SERVER_URL": server_url,
        "PUFFO_CORE_KEYSTORE_DIR": keystore_dir,
        "PUFFO_WORKSPACE": workspace,
        "PUFFO_DATA_SERVICE_URL": data_service_url,
        "PUFFO_RPC_URL": rpc_url,
        LOCAL_SERVICE_TOKEN_ENV: issue_local_service_token(effective_agent_id),
        **_python_user_base_env(runtime_kind),
    }
    # The MCP starts with the agent workspace as cwd. A relative PYTHONPATH
    # would therefore resolve against the wrong directory and can silently
    # load a different editable checkout than the daemon.
    pythonpath = _mcp_pythonpath(runtime_kind)
    if pythonpath:
        env["PYTHONPATH"] = pythonpath
    if agent_id:
        env["PUFFO_AGENT_ID"] = agent_id
    if space_id:
        env["PUFFO_CORE_SPACE_ID"] = space_id
    if runtime_kind:
        env["PUFFO_RUNTIME_KIND"] = runtime_kind
    if harness:
        env["PUFFO_HARNESS"] = harness
    if memory_dir:
        env["PUFFO_MEMORY_DIR"] = memory_dir
    # T23 phase-2: the cli-local / cli-docker worker call sites now
    # forward ``pc.transport``. Only ``bridge`` flips the subprocess to
    # keyless (``puffo_core_server.build_server`` does
    # ``keyless=(transport == "bridge")``), so emit the env var only for
    # bridge. Native agents (the default transport, a truthy string)
    # therefore stay byte-for-byte identical — no PUFFO_CORE_TRANSPORT
    # key, subprocess keeps ``keyless=False`` and its signed keystore
    # path.
    if transport == "bridge":
        env["PUFFO_CORE_TRANSPORT"] = transport
    # Test-only egress shim: forward PUFFO_LOCAL_SANDBOX_TOKEN into the
    # subprocess so its keyless http client can simulate the E2B egress
    # token injection against a local server. Guarded on presence in the
    # daemon environment — production leaves it unset, so nothing is
    # written to any config file.
    import os as _os
    local_sandbox_token = _os.environ.get("PUFFO_LOCAL_SANDBOX_TOKEN")
    if local_sandbox_token:
        env["PUFFO_LOCAL_SANDBOX_TOKEN"] = local_sandbox_token
    # codex only forwards [mcp_servers.puffo.env] to the subprocess,
    # so CODEX_HOME must be pinned explicitly or list_mcp_servers
    # would read the operator's host config instead of the agent's.
    if harness == "codex" and workspace:
        from pathlib import Path as _Path
        env["CODEX_HOME"] = str(_Path(workspace).parent / ".codex")
    return env
